name: Generate collection, commit and push

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to push to'
        required: true
        default: 'main'
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch }}
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '19'
      - name: Install Dependencies
        run: npm install
      - name: Run Script
        run: npm run generate
      - name: Commit and push if changed
        run: |
          git diff
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff --quiet && git diff --staged --quiet || git commit -m 'Update postman collection'
          git push
          